name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.14'

      - name: Cache uv virtualenv (.venv)
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ runner.arch }}-

      - name: Cache ruff
        uses: actions/cache@v4
        with:
          path: .ruff_cache
          key: ruff-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ruff-${{ runner.os }}-${{ runner.arch }}-
            ruff-${{ runner.os }}-

      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            mypy-${{ runner.os }}-${{ runner.arch }}-
            mypy-${{ runner.os }}-

      - name: Install dependencies (all groups)
        run: |
          uv sync --all-groups --frozen

      - name: Ruff
        env:
          RUFF_CACHE_DIR: .ruff_cache
        run: |
          uv run ruff check .

      - name: Mypy (strict)
        env:
          MYPY_CACHE_DIR: .mypy_cache
        run: |
          uv run mypy . --strict

      - name: Pytest
        env:
          PYTEST_ADDOPTS: -q
        run: |
          uv run pytest
