name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies (all groups)
        run: |
          uv sync --all-groups

      - name: Ruff
        run: |
          uv run ruff check .

      - name: Mypy (strict)
        run: |
          uv run mypy . --strict

      - name: Pytest
        env:
          PYTEST_ADDOPTS: -q
        run: |
          uv run pytest
